//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Welic.App.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Welic.App.Helpers.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age required.
        /// </summary>
        public static string AgeRequired {
            get {
                return ResourceManager.GetString("AgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Button_Contact {
            get {
                return ResourceManager.GetString("Button_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this .
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Pass {
            get {
                return ResourceManager.GetString("Confirm_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birthday.
        /// </summary>
        public static string Date_Birthday {
            get {
                return ResourceManager.GetString("Date_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Welic. We&apos;re glad you&apos;re here.
        ///
        ///Welic was born from a dream, the dream of bringing to all people training and events independent of their location and language. It was also born from the dream of providing specialists with unique knowledge, the tools needed to enable them to monetize their knowledge through a Universal work tool - The Internet.
        ///
        ///Our mission is to bring all people unique Trainings and Events in their own language and provide experts with the technological tools necessary to gr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc_About {
            get {
                return ResourceManager.GetString("Desc_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor in Information Systems (PUC-Minas / Uniube), electronics technician (State Technical Industrial School Professor Fontes). As an IT Specialist my academic, human and work training focused on the development and implementation of large projects. I have experience in contact with international companies. I am a professional committed to innovation, leadership and teamwork. Recognized throughout my career by professionalism, steep learning curve as well, by the results obtained..
        /// </summary>
        public static string Desc_André {
            get {
                return ResourceManager.GetString("Desc_André", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us for more details on Welic.
        /// </summary>
        public static string Desc_Contact {
            get {
                return ResourceManager.GetString("Desc_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional with Post-Graduation in Software Engineering by UFMG - Federal University of Minas Gerais and with Graduation in Information Technology by the University Center Newton Paiva.
        ///
        ///He has 21 years of experience in large IT projects and startups, working in the commercial and technical areas for clients of the Public Sector and Private Sector. In the commercial area he served as Executive Customers, Pre-Sales and Business Consultant for Application opportunities, infrastructure and products during  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc_Ederson {
            get {
                return ResourceManager.GetString("Desc_Ederson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joel Serrano has been an entrepreneur for more than 16 years. Graduated in Information Technology and specializing in e-learning. Still, he is a professional with high experience in Consulting and Training of Young and Adults.
        ///
        ///During his professional career, he founded several companies in countries such as Portugal, Holland and Germany.
        ///
        ///At the moment it coordinates a European project, in 5 European countries, in which it stimulates the entrepreneurship in young people in Europe.
        ///
        ///In addition, it ow [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc_Joel {
            get {
                return ResourceManager.GetString("Desc_Joel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor in systems analysis and development at Uniube - University of Uberaba, Brazil. Mobile and Desktop Development Specialist working in the field since 2015. Participant in the .Net community looking to always help improve this universe of development.
        ///
        ///Welic founder member of Welic as CTO..
        /// </summary>
        public static string Desc_Lucas {
            get {
                return ResourceManager.GetString("Desc_Lucas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect?.
        /// </summary>
        public static string Desconnect {
            get {
                return ResourceManager.GetString("Desconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Course.
        /// </summary>
        public static string Detail_course {
            get {
                return ResourceManager.GetString("Detail_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Book.
        /// </summary>
        public static string EBook {
            get {
                return ResourceManager.GetString("EBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Invalid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to authenticate user.
        /// </summary>
        public static string Error_Authenticate_user {
            get {
                return ResourceManager.GetString("Error_Authenticate_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while editing.
        /// </summary>
        public static string Error_Change {
            get {
                return ResourceManager.GetString("Error_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating.
        /// </summary>
        public static string Error_Create {
            get {
                return ResourceManager.GetString("Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Excluding!.
        /// </summary>
        public static string Error_Deleting {
            get {
                return ResourceManager.GetString("Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FirstNameLong {
            get {
                return ResourceManager.GetString("FirstNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galery.
        /// </summary>
        public static string Galery {
            get {
                return ResourceManager.GetString("Galery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Am?.
        /// </summary>
        public static string I_am {
            get {
                return ResourceManager.GetString("I_am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Lançamento {
            get {
                return ResourceManager.GetString("Lançamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Acess.
        /// </summary>
        public static string LastAcess {
            get {
                return ResourceManager.GetString("LastAcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasted Listings.
        /// </summary>
        public static string Lasted_Listing {
            get {
                return ResourceManager.GetString("Lasted_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listings .
        /// </summary>
        public static string Listings {
            get {
                return ResourceManager.GetString("Listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in .
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Listings.
        /// </summary>
        public static string My_Listting {
            get {
                return ResourceManager.GetString("My_Listting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account .
        /// </summary>
        public static string New_Account {
            get {
                return ResourceManager.GetString("New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Here?.
        /// </summary>
        public static string NewHere {
            get {
                return ResourceManager.GetString("NewHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete this Course because there are Videos linked to it yet.
        /// </summary>
        public static string Not_Delete_Courses {
            get {
                return ResourceManager.GetString("Not_Delete_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain:.
        /// </summary>
        public static string Password_contain {
            get {
                return ResourceManager.GetString("Password_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special character (@ # $!).
        /// </summary>
        public static string Password_Especial {
            get {
                return ResourceManager.GetString("Password_Especial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        public static string Password_not_Match {
            get {
                return ResourceManager.GetString("Password_not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number and a minimum of 8 characters.
        /// </summary>
        public static string Password_Number_Length {
            get {
                return ResourceManager.GetString("Password_Number_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Tiny Letter.
        /// </summary>
        public static string Password_Tiny {
            get {
                return ResourceManager.GetString("Password_Tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Uppercase Letter.
        /// </summary>
        public static string Password_Upper {
            get {
                return ResourceManager.GetString("Password_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password weak.
        /// </summary>
        public static string Password_Weak {
            get {
                return ResourceManager.GetString("Password_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish new Listing.
        /// </summary>
        public static string Publish_Listing {
            get {
                return ResourceManager.GetString("Publish_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to log in again.
        /// </summary>
        public static string Reelogar {
            get {
                return ResourceManager.GetString("Reelogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to add a .
        /// </summary>
        public static string Require_Add {
            get {
                return ResourceManager.GetString("Require_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Required Description!.
        /// </summary>
        public static string Require_Description {
            get {
                return ResourceManager.GetString("Require_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary inform the E-mail Adress.
        /// </summary>
        public static string Require_Email {
            get {
                return ResourceManager.GetString("Require_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary Inform the First Name.
        /// </summary>
        public static string Require_FirstName {
            get {
                return ResourceManager.GetString("Require_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary Inform the Last Name.
        /// </summary>
        public static string Require_LastName {
            get {
                return ResourceManager.GetString("Require_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary Inform the Password!.
        /// </summary>
        public static string Require_Password {
            get {
                return ResourceManager.GetString("Require_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Required Title!.
        /// </summary>
        public static string Require_Title {
            get {
                return ResourceManager.GetString("Require_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary Inform the Phone Number.
        /// </summary>
        public static string Requite_phone {
            get {
                return ResourceManager.GetString("Requite_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your listings....
        /// </summary>
        public static string Search_List {
            get {
                return ResourceManager.GetString("Search_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Listings.
        /// </summary>
        public static string See_All_Listings {
            get {
                return ResourceManager.GetString("See_All_Listings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In With Facebook.
        /// </summary>
        public static string SignInFace {
            get {
                return ResourceManager.GetString("SignInFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In With Google.
        /// </summary>
        public static string SignInGoogle {
            get {
                return ResourceManager.GetString("SignInGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In With Email Adress.
        /// </summary>
        public static string SignInMail {
            get {
                return ResourceManager.GetString("SignInMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Successfully.
        /// </summary>
        public static string Success_Change {
            get {
                return ResourceManager.GetString("Success_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with Success.
        /// </summary>
        public static string Success_Create {
            get {
                return ResourceManager.GetString("Success_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsUse {
            get {
                return ResourceManager.GetString("TermsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Welic.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
