//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT mu.IdMenu as Id,
        ///	                 m.Title,
        ///	                 m.IconMenu,
        ///	                 m.Nivel, 
        ///	                 m.DadId,
        ///	                 m.Action,
        ///	                 m.Controller
        ///                FROM dbo.MenusUser mu
        ///                join dbo.MasterMenus m on (m.IdMenu = mu.IdMenu) 
        ///               WHERE Mu.IdUser = @IdUser
        ///               ORDER BY M.Nivel
        ///    .
        /// </summary>
        internal static string Q001 {
            get {
                return ResourceManager.GetString("Q001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  l.title, l.Description, l.UrlDestino, l.Id, l.Prince, l.[Print], l.theme
        ///  from dbo.lives as l
        /// where (l.Title LIKE &apos;%&apos;+@text+&apos;%&apos;) or (l.Description like &apos;%&apos;+@text+&apos;%&apos;) or (l.Theme like &apos;%&apos;+@text+&apos;%&apos;).
        /// </summary>
        internal static string Q002 {
            get {
                return ResourceManager.GetString("Q002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select E.Title, E.Description, E.UrlDestino, E.Prince, E.[Print]
        ///from dbo.Ebooks E
        ///where (E.Title Like  &apos;%&apos;+@text+&apos;%&apos;) or (E.Description like &apos;%&apos;+@text+&apos;%&apos;) or (E.Theme like &apos;%&apos;+@text+&apos;%&apos;).
        /// </summary>
        internal static string Q003 {
            get {
                return ResourceManager.GetString("Q003", resourceCulture);
            }
        }
    }
}
