// <auto-generated />
namespace Welic.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class crrecao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crrecao));
        
        string IMigrationMetadata.Id
        {
            get { return "201812022213083_crrecao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
