//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Classes.RecursosGenericos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntitiesSGA : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntitiesSGA object using the connection string found in the 'EntitiesSGA' section of the application configuration file.
        /// </summary>
        public EntitiesSGA() : base("name=EntitiesSGA", "EntitiesSGA")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntitiesSGA object.
        /// </summary>
        public EntitiesSGA(string connectionString) : base(connectionString, "EntitiesSGA")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntitiesSGA object.
        /// </summary>
        public EntitiesSGA(EntityConnection connection) : base(connection, "EntitiesSGA")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AREAS> AREAS
        {
            get
            {
                if ((_AREAS == null))
                {
                    _AREAS = base.CreateObjectSet<AREAS>("AREAS");
                }
                return _AREAS;
            }
        }
        private ObjectSet<AREAS> _AREAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CUSTOS_DIRETOS> CUSTOS_DIRETOS
        {
            get
            {
                if ((_CUSTOS_DIRETOS == null))
                {
                    _CUSTOS_DIRETOS = base.CreateObjectSet<CUSTOS_DIRETOS>("CUSTOS_DIRETOS");
                }
                return _CUSTOS_DIRETOS;
            }
        }
        private ObjectSet<CUSTOS_DIRETOS> _CUSTOS_DIRETOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ITENS_CUSTOS_DIRETOS> ITENS_CUSTOS_DIRETOS
        {
            get
            {
                if ((_ITENS_CUSTOS_DIRETOS == null))
                {
                    _ITENS_CUSTOS_DIRETOS = base.CreateObjectSet<ITENS_CUSTOS_DIRETOS>("ITENS_CUSTOS_DIRETOS");
                }
                return _ITENS_CUSTOS_DIRETOS;
            }
        }
        private ObjectSet<ITENS_CUSTOS_DIRETOS> _ITENS_CUSTOS_DIRETOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UNIDADES_CUSTOS_DIRETOS> UNIDADES_CUSTOS_DIRETOS
        {
            get
            {
                if ((_UNIDADES_CUSTOS_DIRETOS == null))
                {
                    _UNIDADES_CUSTOS_DIRETOS = base.CreateObjectSet<UNIDADES_CUSTOS_DIRETOS>("UNIDADES_CUSTOS_DIRETOS");
                }
                return _UNIDADES_CUSTOS_DIRETOS;
            }
        }
        private ObjectSet<UNIDADES_CUSTOS_DIRETOS> _UNIDADES_CUSTOS_DIRETOS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AREAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAREAS(AREAS aREAS)
        {
            base.AddObject("AREAS", aREAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CUSTOS_DIRETOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCUSTOS_DIRETOS(CUSTOS_DIRETOS cUSTOS_DIRETOS)
        {
            base.AddObject("CUSTOS_DIRETOS", cUSTOS_DIRETOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ITENS_CUSTOS_DIRETOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToITENS_CUSTOS_DIRETOS(ITENS_CUSTOS_DIRETOS iTENS_CUSTOS_DIRETOS)
        {
            base.AddObject("ITENS_CUSTOS_DIRETOS", iTENS_CUSTOS_DIRETOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UNIDADES_CUSTOS_DIRETOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUNIDADES_CUSTOS_DIRETOS(UNIDADES_CUSTOS_DIRETOS uNIDADES_CUSTOS_DIRETOS)
        {
            base.AddObject("UNIDADES_CUSTOS_DIRETOS", uNIDADES_CUSTOS_DIRETOS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSGA", Name="AREAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AREAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AREAS object.
        /// </summary>
        /// <param name="aREA">Initial value of the AREA property.</param>
        public static AREAS CreateAREAS(global::System.Int32 aREA)
        {
            AREAS aREAS = new AREAS();
            aREAS.AREA = aREA;
            return aREAS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AREA
        {
            get
            {
                return _AREA;
            }
            set
            {
                if (_AREA != value)
                {
                    OnAREAChanging(value);
                    ReportPropertyChanging("AREA");
                    _AREA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AREA");
                    OnAREAChanged();
                }
            }
        }
        private global::System.Int32 _AREA;
        partial void OnAREAChanging(global::System.Int32 value);
        partial void OnAREAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSGA", Name="CUSTOS_DIRETOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CUSTOS_DIRETOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CUSTOS_DIRETOS object.
        /// </summary>
        /// <param name="cUSTO">Initial value of the CUSTO property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        public static CUSTOS_DIRETOS CreateCUSTOS_DIRETOS(global::System.Int32 cUSTO, global::System.String dESCRICAO)
        {
            CUSTOS_DIRETOS cUSTOS_DIRETOS = new CUSTOS_DIRETOS();
            cUSTOS_DIRETOS.CUSTO = cUSTO;
            cUSTOS_DIRETOS.DESCRICAO = dESCRICAO;
            return cUSTOS_DIRETOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CUSTO
        {
            get
            {
                return _CUSTO;
            }
            set
            {
                if (_CUSTO != value)
                {
                    OnCUSTOChanging(value);
                    ReportPropertyChanging("CUSTO");
                    _CUSTO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CUSTO");
                    OnCUSTOChanged();
                }
            }
        }
        private global::System.Int32 _CUSTO;
        partial void OnCUSTOChanging(global::System.Int32 value);
        partial void OnCUSTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSGA", Name="ITENS_CUSTOS_DIRETOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ITENS_CUSTOS_DIRETOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ITENS_CUSTOS_DIRETOS object.
        /// </summary>
        /// <param name="iTEM">Initial value of the ITEM property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        public static ITENS_CUSTOS_DIRETOS CreateITENS_CUSTOS_DIRETOS(global::System.Int32 iTEM, global::System.String dESCRICAO)
        {
            ITENS_CUSTOS_DIRETOS iTENS_CUSTOS_DIRETOS = new ITENS_CUSTOS_DIRETOS();
            iTENS_CUSTOS_DIRETOS.ITEM = iTEM;
            iTENS_CUSTOS_DIRETOS.DESCRICAO = dESCRICAO;
            return iTENS_CUSTOS_DIRETOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ITEM
        {
            get
            {
                return _ITEM;
            }
            set
            {
                if (_ITEM != value)
                {
                    OnITEMChanging(value);
                    ReportPropertyChanging("ITEM");
                    _ITEM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ITEM");
                    OnITEMChanged();
                }
            }
        }
        private global::System.Int32 _ITEM;
        partial void OnITEMChanging(global::System.Int32 value);
        partial void OnITEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelSGA", Name="UNIDADES_CUSTOS_DIRETOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UNIDADES_CUSTOS_DIRETOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UNIDADES_CUSTOS_DIRETOS object.
        /// </summary>
        /// <param name="uNIDADE">Initial value of the UNIDADE property.</param>
        /// <param name="dESCRICAO">Initial value of the DESCRICAO property.</param>
        public static UNIDADES_CUSTOS_DIRETOS CreateUNIDADES_CUSTOS_DIRETOS(global::System.Int32 uNIDADE, global::System.String dESCRICAO)
        {
            UNIDADES_CUSTOS_DIRETOS uNIDADES_CUSTOS_DIRETOS = new UNIDADES_CUSTOS_DIRETOS();
            uNIDADES_CUSTOS_DIRETOS.UNIDADE = uNIDADE;
            uNIDADES_CUSTOS_DIRETOS.DESCRICAO = dESCRICAO;
            return uNIDADES_CUSTOS_DIRETOS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UNIDADE
        {
            get
            {
                return _UNIDADE;
            }
            set
            {
                if (_UNIDADE != value)
                {
                    OnUNIDADEChanging(value);
                    ReportPropertyChanging("UNIDADE");
                    _UNIDADE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UNIDADE");
                    OnUNIDADEChanged();
                }
            }
        }
        private global::System.Int32 _UNIDADE;
        partial void OnUNIDADEChanging(global::System.Int32 value);
        partial void OnUNIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion
    
    }

    #endregion
    
}
